# -*- coding: utf-8 -*-
"""SEGDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m9Yc6AJKbl8A2g8WVHPwk-ov4Jm0mvhT

# **SEGDA v7.6 - CAMERA-READY VISUAL PIPELINE**
"""

# Commented out IPython magic to ensure Python compatibility.

# -*- coding: utf-8 -*-
"""
SEGDA AUDITED REPRODUCIBILITY + LNICST CAMERA-READY VISUAL PIPELINE
=============================================

Socio-Environmental Grid Disruption Analysis (SEGDA)
California, 2018–2023

PRIMARY AUDITED METHOD
----------------------
1. Tract EJBI requires all three components:
   - CDC/ATSDR SVI RPL_THEMES
   - CalEnviroScreen overall percentile (CIscoreP / 100)
   - CalEnviroScreen Pollution Burden percentile (Pollution_Pctl / 100)
   Negative SVI codes are treated as missing.

2. County EJBI = population-weighted mean of valid tract EJBI.

3. Study-defined classifications are called "High-EJBI":
   - tract High-EJBI: numeric EJBI >= 0.75
   - county High-EJBI: county numeric EJBI >= 0.60
   These are NOT official California SB 535 DAC designations.

4. Primary outage burden:
   - start from eaglei_transformed.csv
   - deduplicate underlying reconstructed EAGLE-I episodes BEFORE OE-417 join expansion
   - estimated customer-outage-hours = mean_customers * duration
   - primary denominator = ORNL Modeled County Customers (MCC)
   - primary OBI = robust IQR normalization of COH per modeled customer

5. Sensitivity models:
   - population-normalized outage burden
   - MCC-normalized burden excluding episodes at the apparent 34-hour ceiling

6. Climate Stress:
   unweighted mean of min-max normalized FEMA NRI risk scores:
   drought, heat wave, wildfire, riverine flood, earthquake, strong wind, tornado.

7. EIA-861 remains excluded from the PRIMARY OBI, but v7.1 includes a validated
   historical sensitivity branch based on 2018-2023 county reliability estimates.
   County-year EIA SAIDI values are admitted only when >=80% of estimated county
   customer mass is covered by reporting utilities, and the 6-year reliability
   index requires >=4 qualifying years. The 70/30 EAGLE-I/EIA model is reported
   as a sensitivity result, not assumed as the primary index.

8. GRIP is intentionally excluded from the locked quantitative results until
   individual project claims are verified from official DOE project records.

COLAB EXECUTION
---------------
Upload this .py file and the required datasets, then run ONE of:
#     %run SEGDA.py

OUTPUTS
-------
- tract metrics
- county metrics
- Tables II–VI
- sensitivity correlations
- QA / provenance report
- core publication figures
- validation report

Author: Victoria Love Franklin
Audit + visual QA pipeline generated 2026.
"""

import os
import sys
import json
import hashlib
import warnings
import shutil
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Patch
from matplotlib.text import Text
from scipy import stats

SCRIPT_VERSION = "7.6.6"
STUDY_START = 2018
STUDY_END = 2023
TRACT_HIGH_EJBI_THRESHOLD = 0.75
COUNTY_HIGH_EJBI_THRESHOLD = 0.60

# Expected locked results from independent audit. These are guardrails, not inputs.
EXPECTED = {
    "tract_geometry_n": 8057,
    "strict_ejbi_n": 7931,
    "high_ejbi_tracts": 1690,
    "county_n": 58,
    "high_ejbi_counties": 11,
    "maup_suppression_pct": 67.820136,
    "ejbi_obi_r": -0.441924,
    "climate_obi_r": -0.565268,
    "eia30_ejbi_r": -0.550667,
    "eia30_climate_r": -0.646013,
    "hidden_high_ejbi_tracts": 431,
    "svi_ejbi_r": 0.829048,
    "svi_ejbi_agreement_pct": 86.2069,
    "ejbi_moran_i": 0.201658,
    "obi_moran_i": 0.401040,
}

def _default_data_dir():
    """Choose a sensible runtime data directory without overriding SEGDA_DATA_DIR."""
    env = os.environ.get("SEGDA_DATA_DIR")
    if env:
        return Path(env).expanduser().resolve()
    # Google Colab default.
    if Path("/content").exists():
        return Path("/content")
    # Local/script execution: use the script's directory.
    return Path(__file__).resolve().parent

BASE = _default_data_dir()
OUT = Path(os.environ.get("SEGDA_OUTPUT_DIR", str(BASE / "SEGDA_v7_6_OUTPUT"))).expanduser()
FIG = OUT / "figures"
TABLE_DIR = OUT / "tables"
VALIDATION_DIR = OUT / "validation"
DATA_DIR = OUT / "data_products"
MANIFEST_DIR = OUT / "manifests"
RESULTS_DIR = OUT / "results"
EXPORT_DIR = OUT / "export_bundle"

for _d in (OUT, FIG, TABLE_DIR, VALIDATION_DIR, DATA_DIR, MANIFEST_DIR, RESULTS_DIR, EXPORT_DIR):
    _d.mkdir(parents=True, exist_ok=True)

warnings.simplefilter("default")
warnings.filterwarnings("ignore", category=DeprecationWarning, module=r"jupyter_client.*")
warnings.filterwarnings("ignore", category=DeprecationWarning, module=r"matplotlib.backends.backend_pdf.*")

def find_existing(candidates):
    for name in candidates:
        p = BASE / name
        if p.exists():
            return p
    raise FileNotFoundError(f"None of these files were found: {candidates}")

def sha256(path, block=1024*1024):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            chunk = f.read(block)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()

def robust_norm_iqr(s):
    s = pd.to_numeric(s, errors="coerce")
    q1, q3 = s.quantile([0.25, 0.75])
    iqr = q3 - q1
    if pd.isna(iqr) or iqr == 0:
        return pd.Series(np.nan, index=s.index, dtype=float)
    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr
    clipped = s.clip(lo, hi)
    mn, mx = clipped.min(skipna=True), clipped.max(skipna=True)
    if pd.isna(mn) or pd.isna(mx) or mx == mn:
        return pd.Series(np.nan, index=s.index, dtype=float)
    return (clipped - mn) / (mx - mn)

def minmax(s):
    s = pd.to_numeric(s, errors="coerce")
    mn, mx = s.min(skipna=True), s.max(skipna=True)
    if pd.isna(mn) or pd.isna(mx) or mx == mn:
        return pd.Series(np.nan, index=s.index, dtype=float)
    return (s - mn) / (mx - mn)

REQUIRED_INPUTS = {
    "ces": ["CalEnviroScreen_4.0.csv"],
    "svi_tract": ["SVI_CA_TRACT.csv"],
    "svi_county": ["California_SVI_2022.csv"],
    "tract_shp": ["tl_2019_06_tract.shp", "tl_2019_06_tract(1).shp"],
    "county_shp": ["tl_2019_us_county.shp", "tl_2019_us_county(1).shp"],
    "mcc": ["MCC.csv"],
    "nri": ["NRI_Table_Counties_California.csv"],
    "eaglei_transformed": ["eaglei_transformed.csv"],
    "eia_historical_summary": ["SEGDA_EIA861_CA_COUNTY_RELIABILITY_6YR_SUMMARY.csv"],
}

def preflight_inputs():
    """Resolve every required input and report all missing files in one error."""
    resolved, missing = {}, {}
    for role, candidates in REQUIRED_INPUTS.items():
        hit = next((BASE / name for name in candidates if (BASE / name).exists()), None)
        if hit is None:
            missing[role] = candidates
        else:
            resolved[role] = hit

    report = {
        "script_version": SCRIPT_VERSION,
        "data_directory": str(BASE),
        "output_directory": str(OUT),
        "resolved": {k: str(v) for k, v in resolved.items()},
        "missing": missing,
        "preflight_pass": not bool(missing),
    }
    with open(MANIFEST_DIR / "input_preflight.json", "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)

    if missing:
        lines = [
            f"SEGDA input preflight failed. Data directory: {BASE}",
            "Missing required inputs:"
        ]
        for role, candidates in missing.items():
            lines.append(f"  - {role}: one of {candidates}")
        lines += [
            "",
            "Place the dataset bundle in the data directory or set SEGDA_DATA_DIR",
            "to the folder containing these files, then rerun the script."
        ]
        raise FileNotFoundError("\n".join(lines))
    return resolved

def load_inputs():
    return preflight_inputs()


def save_csv_export(df, filename, category="results", index=False):
    """
    Save a CSV to BOTH the root output directory and its organized subdirectory.
    This makes Colab file-browser discovery simple while keeping the output bundle tidy.
    """
    root_path = OUT / filename
    if category == "tables":
        subdir = TABLE_DIR
    elif category == "validation":
        subdir = VALIDATION_DIR
    elif category == "data":
        subdir = DATA_DIR
    else:
        subdir = RESULTS_DIR
    sub_path = subdir / filename

    df.to_csv(root_path, index=index)
    if sub_path != root_path:
        df.to_csv(sub_path, index=index)

    if not root_path.exists() or root_path.stat().st_size == 0:
        raise IOError(f"CSV export failed: {root_path}")
    if not sub_path.exists() or sub_path.stat().st_size == 0:
        raise IOError(f"CSV export failed: {sub_path}")
    return root_path, sub_path


def finalize_export_bundle():
    """
    Create a complete downloadable ZIP after every successful run.
    The ZIP is placed beside the output directory, not inside it.
    """
    # Copy top-level result files into export_bundle/results for a single clean bundle view.
    bundle_results = EXPORT_DIR / "data_and_results"
    bundle_results.mkdir(parents=True, exist_ok=True)

    for p in OUT.iterdir():
        if p.is_file() and p.suffix.lower() in {".csv", ".json", ".txt"}:
            shutil.copy2(p, bundle_results / p.name)

    # Copy organized directories into export bundle.
    for name, source in [
        ("tables", TABLE_DIR),
        ("validation", VALIDATION_DIR),
        ("data_products", DATA_DIR),
        ("results", RESULTS_DIR),
        ("manifests", MANIFEST_DIR),
    ]:
        target = EXPORT_DIR / name
        if target.exists():
            shutil.rmtree(target)
        shutil.copytree(source, target)

    # Figures stay in their existing high-resolution folders and are also copied into the bundle.
    target_fig = EXPORT_DIR / "figures"
    if target_fig.exists():
        shutil.rmtree(target_fig)
    shutil.copytree(FIG, target_fig)

    zip_base = OUT.parent / OUT.name
    zip_path = Path(shutil.make_archive(str(zip_base), "zip", root_dir=OUT))

    if not zip_path.exists() or zip_path.stat().st_size == 0:
        raise IOError(f"ZIP export failed: {zip_path}")

    return zip_path


def build_provenance(paths):
    rows = []
    for role, p in paths.items():
        rows.append({
            "role": role,
            "file": p.name,
            "path": str(p),
            "size_bytes": p.stat().st_size,
            "sha256": sha256(p),
        })
    df = pd.DataFrame(rows)
    save_csv_export(df, "v7_input_provenance.csv", category="results", index=False)
    return df

def build_tract_ejbi(paths):
    ces = pd.read_csv(paths["ces"], low_memory=False)
    svi = pd.read_csv(paths["svi_tract"], low_memory=False)
    tracts = gpd.read_file(paths["tract_shp"])[["GEOID", "geometry"]].copy()
    tracts["GEOID"] = tracts["GEOID"].astype(str).str.zfill(11)

    cx = pd.DataFrame({
        "GEOID": ces["Tract"].astype(str).str.replace(r"\.0$", "", regex=True).str.zfill(11),
        "population": pd.to_numeric(ces["Population"], errors="coerce"),
        "CES": pd.to_numeric(ces["CIscoreP"], errors="coerce") / 100.0,
        "Pollution": pd.to_numeric(ces["Pollution_Pctl"], errors="coerce") / 100.0,
    }).drop_duplicates("GEOID")

    sx = pd.DataFrame({
        "GEOID": svi["FIPS"].astype(str).str.replace(r"\.0$", "", regex=True).str.zfill(11),
        "SVI": pd.to_numeric(svi["RPL_THEMES"], errors="coerce"),
    }).drop_duplicates("GEOID")
    sx.loc[sx["SVI"] < 0, "SVI"] = np.nan

    t = tracts.merge(cx, on="GEOID", how="left").merge(sx, on="GEOID", how="left")
    t["components_present"] = t[["SVI", "CES", "Pollution"]].notna().sum(axis=1)
    t["EJBI"] = t[["SVI", "CES", "Pollution"]].mean(axis=1, skipna=False)
    t["county_fips"] = t["GEOID"].str[:5]
    t["High_EJBI_tract"] = pd.Series(pd.NA, index=t.index, dtype="Int64")
    ok = t["EJBI"].notna()
    t.loc[ok, "High_EJBI_tract"] = (t.loc[ok, "EJBI"] >= TRACT_HIGH_EJBI_THRESHOLD).astype(int)

    # Explicit percentile-rank sensitivity; never silently substituted for numeric EJBI.
    t["EJBI_percentile_rank"] = np.nan
    t.loc[ok, "EJBI_percentile_rank"] = t.loc[ok, "EJBI"].rank(method="average", pct=True)

    return t

def build_county_ejbi(tracts, paths):
    valid = tracts.dropna(subset=["EJBI"]).copy()
    valid["weight"] = valid["population"].fillna(1)

    def agg(g):
        if g["weight"].sum() > 0:
            score = np.average(g["EJBI"], weights=g["weight"])
        else:
            score = g["EJBI"].mean()
        return pd.Series({
            "EJBI": score,
            "n_valid_tracts": len(g),
            "n_high_ejbi_tracts": int((g["EJBI"] >= TRACT_HIGH_EJBI_THRESHOLD).sum()),
            "county_population": g["population"].sum(),
        })

    county = valid.groupby("county_fips").apply(agg, include_groups=False).reset_index()

    cg = gpd.read_file(paths["county_shp"]).copy()
    # California FIPS filtering for national county shapefile.
    state_col = "STATEFP" if "STATEFP" in cg.columns else None
    if state_col:
        cg = cg[cg[state_col].astype(str).str.zfill(2) == "06"].copy()

    # Geometry QA: spatial statistics require a complete, valid 58-county layer.
    if len(cg) != 58:
        raise ValueError(
            f"County shapefile QA failed: expected 58 California counties, found {len(cg)}. "
            "Use the complete 2019 TIGER/Line county shapefile bundle."
        )
    missing_geom = cg.geometry.isna()
    empty_geom = cg.geometry.apply(lambda geom: geom is not None and geom.is_empty)
    if bool((missing_geom | empty_geom).any()):
        bad_names = []
        if "NAME" in cg.columns:
            bad_names = cg.loc[missing_geom | empty_geom, "NAME"].astype(str).tolist()
        raise ValueError(
            "County shapefile QA failed: missing/empty geometry detected"
            + (f" for: {', '.join(bad_names)}" if bad_names else "")
            + ". Make sure .shp, .shx, .dbf, .prj, and .cpg files are together."
        )

    invalid_geom = ~cg.geometry.is_valid
    if bool(invalid_geom.any()):
        try:
            cg.loc[invalid_geom, "geometry"] = cg.loc[invalid_geom, "geometry"].make_valid()
        except Exception:
            cg.loc[invalid_geom, "geometry"] = cg.loc[invalid_geom, "geometry"].buffer(0)

    if "GEOID" in cg.columns:
        cg["county_fips"] = cg["GEOID"].astype(str).str.zfill(5)
    elif {"STATEFP","COUNTYFP"}.issubset(cg.columns):
        cg["county_fips"] = cg["STATEFP"].astype(str).str.zfill(2) + cg["COUNTYFP"].astype(str).str.zfill(3)
    else:
        raise ValueError("County shapefile lacks usable FIPS fields.")

    name_col = "NAME" if "NAME" in cg.columns else None
    keep = ["county_fips", "geometry"] + ([name_col] if name_col else [])
    cg = cg[keep].copy()
    if name_col:
        cg = cg.rename(columns={name_col: "county"})
    county = cg.merge(county, on="county_fips", how="left")
    county["High_EJBI_county"] = (county["EJBI"] >= COUNTY_HIGH_EJBI_THRESHOLD).astype("Int64")
    return county

def clean_eaglei_episodes(paths):
    e = pd.read_csv(paths["eaglei_transformed"], low_memory=False)

    required = ["fips","state","county","start_time","duration","min_customers","max_customers","mean_customers"]
    missing = [c for c in required if c not in e.columns]
    if missing:
        raise ValueError(f"Transformed EAGLE-I missing required episode fields: {missing}")

    e["start_time"] = pd.to_datetime(e["start_time"], errors="coerce", utc=True)
    if "end_time" in e.columns:
        e["end_time"] = pd.to_datetime(e["end_time"], errors="coerce", utc=True)

    for c in ["fips","duration","min_customers","max_customers","mean_customers"]:
        e[c] = pd.to_numeric(e[c], errors="coerce")

    episode_key = required.copy()
    multiplicity = e.groupby(episode_key, dropna=False).size().reset_index(name="source_row_multiplicity")

    # Prefer a row without OE-417 linkage when a duplicate group contains one.
    oe_cols = [c for c in ["event_id","state_event","Datetime Event Began","Datetime Restoration","Event Type"] if c in e.columns]
    e["_has_oe417"] = e[oe_cols].notna().any(axis=1) if oe_cols else False
    e = e.sort_values(episode_key + ["_has_oe417"], ascending=[True]*len(episode_key)+[True], kind="stable")
    e = e.drop_duplicates(subset=episode_key, keep="first").copy()
    e = e.merge(multiplicity, on=episode_key, how="left", validate="one_to_one")
    e.drop(columns=["_has_oe417"], inplace=True, errors="ignore")

    e["year"] = e["start_time"].dt.year
    e = e[e["year"].between(STUDY_START, STUDY_END)].copy()
    e["county_fips"] = pd.to_numeric(e["fips"], errors="coerce").astype("Int64").astype(str).str.zfill(5)
    e["estimated_customer_outage_hours"] = e["mean_customers"] * e["duration"]

    # QA flags preserve known transformation artifacts rather than "correcting" unknown upstream choices.
    e["qa_min_customers_at_200"] = np.isclose(e["min_customers"], 200, equal_nan=False)
    e["qa_duration_at_34h"] = np.isclose(e["duration"], 34, equal_nan=False)
    max_ceiling = e["max_customers"].max(skipna=True)
    e["qa_max_customers_at_dataset_ceiling"] = np.isclose(e["max_customers"], max_ceiling, equal_nan=False)

    return e

def build_outage_burden(episodes, paths):
    burden = episodes.groupby("county_fips", as_index=False).agg(
        estimated_customer_outage_hours=("estimated_customer_outage_hours","sum"),
        reconstructed_episodes=("county_fips","size"),
        episodes_at_200_floor=("qa_min_customers_at_200","sum"),
        episodes_at_34h_ceiling=("qa_duration_at_34h","sum"),
        max_prior_join_multiplicity=("source_row_multiplicity","max"),
    )

    unc = episodes[~episodes["qa_duration_at_34h"]].groupby(
        "county_fips", as_index=False
    )["estimated_customer_outage_hours"].sum().rename(
        columns={"estimated_customer_outage_hours":"estimated_coh_excl34"}
    )
    burden = burden.merge(unc, on="county_fips", how="left")

    mcc = pd.read_csv(paths["mcc"], low_memory=False)
    mcc["county_fips"] = mcc["County_FIPS"].astype(str).str.replace(r"\.0$", "", regex=True).str.zfill(5)
    mcc["modeled_customers"] = pd.to_numeric(mcc["Customers"], errors="coerce")
    mcc = mcc[mcc["county_fips"].str.startswith("06")].groupby(
        "county_fips", as_index=False
    )["modeled_customers"].sum()

    burden = burden.merge(mcc, on="county_fips", how="left")
    burden["coh_per_mcc"] = burden["estimated_customer_outage_hours"] / burden["modeled_customers"]
    burden["OBI_MCC"] = robust_norm_iqr(burden["coh_per_mcc"])
    burden["coh_per_mcc_excl34"] = burden["estimated_coh_excl34"] / burden["modeled_customers"]
    burden["OBI_MCC_EXCL34"] = robust_norm_iqr(burden["coh_per_mcc_excl34"])
    return burden

def build_climate(paths):
    n = pd.read_csv(paths["nri"], low_memory=False)
    n["county_fips"] = n["STCOFIPS"].astype(str).str.replace(r"\.0$", "", regex=True).str.zfill(5)
    hazard_map = {
        "DRGT_RISKS":"drought",
        "HWAV_RISKS":"heat",
        "WFIR_RISKS":"wildfire",
        "RFLD_RISKS":"flood",
        "ERQK_RISKS":"earthquake",
        "SWND_RISKS":"wind",
        "TRND_RISKS":"tornado",
    }
    norm_cols = []
    for source, label in hazard_map.items():
        if source not in n.columns:
            raise ValueError(f"NRI missing required field: {source}")
        col = f"{label}_norm"
        n[col] = minmax(n[source])
        norm_cols.append(col)
    n["Climate_Stress"] = n[norm_cols].mean(axis=1, skipna=True)
    return n[["county_fips","Climate_Stress"] + norm_cols].drop_duplicates("county_fips")

def combine_metrics(county_gdf, burden, climate):
    d = county_gdf.merge(burden, on="county_fips", how="left").merge(climate, on="county_fips", how="left")
    d["coh_per_population"] = d["estimated_customer_outage_hours"] / d["county_population"]
    d["OBI_POP"] = robust_norm_iqr(d["coh_per_population"])
    return d


def attach_eia_historical_sensitivity(counties, paths):
    """
    Join the independently audited 2018-2023 EIA reliability summary.

    The source summary already applies:
      - annual utility-to-county allocation using service-territory constraints,
        annual utility customers, and MCC county totals via IPF/RAS;
      - >=80% SAIDI-reporting customer-mass threshold for county-year inclusion;
      - >=4 qualifying years for the six-year reliability index.

    EIA is sensitivity-only in v7.1.
    """
    eia = pd.read_csv(paths["eia_historical_summary"], low_memory=False)
    keep = [
        "county", "years_with_ge80_coverage", "mean_saidi_2018_2023",
        "median_saidi_2018_2023", "mean_saifi_2018_2023",
        "mean_reporting_coverage_pct", "EIA_RELIABILITY_INDEX_2018_2023"
    ]
    missing = [c for c in keep if c not in eia.columns]
    if missing:
        raise ValueError(f"Historical EIA summary missing required columns: {missing}")

    d = counties.merge(eia[keep], on="county", how="left")

    # Sensitivity branches; 70/30 mirrors the submitted study design but is not primary.
    d["OBI_EIA20"] = 0.80*d["OBI_MCC"] + 0.20*d["EIA_RELIABILITY_INDEX_2018_2023"]
    d["OBI_EIA30"] = 0.70*d["OBI_MCC"] + 0.30*d["EIA_RELIABILITY_INDEX_2018_2023"]
    d["OBI_EIA50"] = 0.50*d["OBI_MCC"] + 0.50*d["EIA_RELIABILITY_INDEX_2018_2023"]
    return d

def correlation_row(df, x, y):
    z = df[[x,y]].dropna()
    r,p = stats.pearsonr(z[x], z[y])
    rho,ps = stats.spearmanr(z[x], z[y])
    return {
        "Variable_1":x, "Variable_2":y, "N":len(z),
        "Pearson_r":r, "Pearson_p":p,
        "Spearman_rho":rho, "Spearman_p":ps,
    }


def bootstrap_corr(df, x, y, nboot=5000, seed=42):
    z = df[[x,y]].dropna().reset_index(drop=True)
    r,p = stats.pearsonr(z[x],z[y])
    rng = np.random.default_rng(seed)
    vals = []
    for _ in range(nboot):
        idx = rng.integers(0, len(z), len(z))
        b = z.iloc[idx]
        if b[x].nunique() > 1 and b[y].nunique() > 1:
            vals.append(stats.pearsonr(b[x],b[y])[0])
    lo,hi = np.quantile(vals,[0.025,0.975])
    return len(z),r,p,lo,hi

def remaining_claims_diagnostics(tracts, counties, paths):
    # Hidden study-defined High-EJBI tracts.
    valid = tracts.dropna(subset=["EJBI"]).copy()
    c = counties[["county_fips","county","EJBI"]].rename(columns={"EJBI":"county_EJBI"})
    h = valid.merge(c,on="county_fips",how="left")
    hidden = h[(h["EJBI"] >= TRACT_HIGH_EJBI_THRESHOLD) &
               (h["county_EJBI"] < COUNTY_HIGH_EJBI_THRESHOLD)].copy()
    hidden_by_county = hidden.groupby(["county_fips","county"]).size().reset_index(
        name="hidden_high_EJBI_tracts").sort_values("hidden_high_EJBI_tracts",ascending=False)

    # County SVI concordance.
    svi = pd.read_csv(paths["svi_county"],low_memory=False)
    svi["county_fips"] = svi["FIPS"].astype(str).str.replace(r"\.0$","",regex=True).str.zfill(5)
    svi["SVI_county"] = pd.to_numeric(svi["RPL_THEMES"],errors="coerce")
    svi.loc[svi["SVI_county"]<0,"SVI_county"] = np.nan
    cs = counties.merge(svi[["county_fips","SVI_county"]],on="county_fips",how="left")
    z = cs[["EJBI","SVI_county"]].dropna()
    r,p = stats.pearsonr(z["EJBI"],z["SVI_county"])
    rho,ps = stats.spearmanr(z["EJBI"],z["SVI_county"])
    cs["SVI_high"] = cs["SVI_county"] >= 0.75
    cs["EJBI_high"] = cs["EJBI"] >= COUNTY_HIGH_EJBI_THRESHOLD
    cs["concordant"] = cs["SVI_high"] == cs["EJBI_high"]
    agreement = 100*cs["concordant"].mean()

    # Corrected effect size for High-EJBI vs other OBI.
    a = counties.loc[counties["EJBI"]>=COUNTY_HIGH_EJBI_THRESHOLD,"OBI_MCC"].dropna().to_numpy()
    b = counties.loc[counties["EJBI"]<COUNTY_HIGH_EJBI_THRESHOLD,"OBI_MCC"].dropna().to_numpy()
    n1,n2 = len(a),len(b)
    pooled = np.sqrt(((n1-1)*np.var(a,ddof=1)+(n2-1)*np.var(b,ddof=1))/(n1+n2-2))
    d = (a.mean()-b.mean())/pooled
    rng=np.random.default_rng(42)
    boots=[]
    for _ in range(5000):
        aa=rng.choice(a,size=n1,replace=True); bb=rng.choice(b,size=n2,replace=True)
        pp=np.sqrt(((n1-1)*np.var(aa,ddof=1)+(n2-1)*np.var(bb,ddof=1))/(n1+n2-2))
        if pp>0 and np.isfinite(pp):
            boots.append((aa.mean()-bb.mean())/pp)
    dlo,dhi=np.quantile(boots,[.025,.975])

    summary = pd.DataFrame([
        ["hidden_high_EJBI_tracts",len(hidden)],
        ["hidden_share_of_high_EJBI_tracts_pct",100*len(hidden)/int((valid["EJBI"]>=TRACT_HIGH_EJBI_THRESHOLD).sum())],
        ["SVI_EJBI_Pearson_r",r],
        ["SVI_EJBI_Pearson_p",p],
        ["SVI_EJBI_Spearman_rho",rho],
        ["SVI_EJBI_agreement_pct",agreement],
        ["both_high",int((cs["SVI_high"]&cs["EJBI_high"]).sum())],
        ["both_low",int((~cs["SVI_high"]&~cs["EJBI_high"]).sum())],
        ["SVI_only_high",int((cs["SVI_high"]&~cs["EJBI_high"]).sum())],
        ["EJBI_only_high",int((~cs["SVI_high"]&cs["EJBI_high"]).sum())],
        ["High_EJBI_vs_other_OBI_Cohen_d",d],
        ["Cohen_d_CI_low",dlo],
        ["Cohen_d_CI_high",dhi],
    ],columns=["metric","value"])
    return summary, hidden_by_county, cs

def build_queen_weights(county_gdf):
    """
    Build row-standardized Queen-contiguity weights with explicit geometry QA.

    v7.6.6 fix:
    Prevents the prior AttributeError: 'NoneType' object has no attribute 'touches'
    by validating every county geometry before any spatial predicate is evaluated.
    """
    if not isinstance(county_gdf, gpd.GeoDataFrame):
        raise TypeError("Queen weights require a GeoDataFrame.")
    if "geometry" not in county_gdf.columns:
        raise ValueError("Queen weights require a geometry column.")

    g = county_gdf.reset_index(drop=True).copy()

    missing = g.geometry.isna()
    empty = g.geometry.apply(lambda geom: geom is not None and geom.is_empty)
    bad = missing | empty
    if bool(bad.any()):
        cols = [c for c in ["county_fips", "county"] if c in g.columns]
        bad_rows = g.loc[bad, cols]
        detail = bad_rows.to_string(index=False) if len(cols) else str(list(g.index[bad]))
        raise ValueError(
            "County geometry QA failed before Queen-contiguity calculation. "
            f"Missing/empty geometries: {int(bad.sum())}\n{detail}\n"
            "Do not drop these counties. Re-extract the complete TIGER/Line county "
            "shapefile (.shp + .shx + .dbf + .prj + .cpg) and rerun."
        )

    invalid = ~g.geometry.is_valid
    if bool(invalid.any()):
        try:
            g.loc[invalid, "geometry"] = g.loc[invalid, "geometry"].make_valid()
        except Exception:
            g.loc[invalid, "geometry"] = g.loc[invalid, "geometry"].buffer(0)

    still_bad = g.geometry.isna() | g.geometry.apply(
        lambda geom: geom is None or geom.is_empty or (not geom.is_valid)
    )
    if bool(still_bad.any()):
        raise ValueError("County geometry repair failed; spatial analysis cannot proceed safely.")

    n = len(g)
    A = np.zeros((n, n), dtype=float)

    for i in range(n):
        gi = g.geometry.iloc[i]
        for j in range(i + 1, n):
            gj = g.geometry.iloc[j]
            if gi.touches(gj):
                A[i, j] = 1.0
                A[j, i] = 1.0

    rs = A.sum(axis=1)
    islands = np.where(rs == 0)[0]
    if len(islands):
        cols = [c for c in ["county_fips", "county"] if c in g.columns]
        detail = g.iloc[islands][cols].to_string(index=False) if cols else str(islands.tolist())
        raise ValueError(
            "Queen-contiguity QA failed: one or more counties have no neighbors.\n"
            f"{detail}\nCheck the county boundary files before computing Moran's I/LISA."
        )

    W = np.divide(A, rs[:, None], out=np.zeros_like(A), where=rs[:, None] > 0)
    return A, W

def global_moran_permutation(x,W,perms=999,seed=42):
    x=np.asarray(x,float); z=x-x.mean(); n=len(x); S0=W.sum()
    I=n/S0*(z@W@z)/(z@z)
    rng=np.random.default_rng(seed)
    sim=np.empty(perms)
    for k in range(perms):
        zp=rng.permutation(z)
        sim[k]=n/S0*(zp@W@zp)/(zp@zp)
    center=sim.mean()
    p=(np.sum(np.abs(sim-center)>=abs(I-center))+1)/(perms+1)
    zscore=(I-sim.mean())/sim.std(ddof=1)
    return I,zscore,p

def local_moran_permutation(x,W,perms=999,seed=42):
    x=np.asarray(x,float)
    z=(x-x.mean())/x.std(ddof=0)
    m2=(z@z)/len(z); lag=W@z; Ii=z*lag/m2
    rng=np.random.default_rng(seed); sim=np.zeros((perms,len(z)))
    for k in range(perms):
        zp=rng.permutation(z)
        sim[k]=zp*(W@zp)/((zp@zp)/len(z))
    center=sim.mean(axis=0)
    p=(np.sum(np.abs(sim-center)>=np.abs(Ii-center),axis=0)+1)/(perms+1)
    quad=np.full(len(z),"NS",dtype=object); sig=p<.05
    quad[sig&(z>0)&(lag>0)]="HH"; quad[sig&(z<0)&(lag<0)]="LL"
    quad[sig&(z>0)&(lag<0)]="HL"; quad[sig&(z<0)&(lag>0)]="LH"
    return Ii,p,quad

def spatial_diagnostics(counties):
    A,_=build_queen_weights(counties)
    summaries=[]; locals_all=[]
    for metric in ["EJBI","OBI_MCC","OBI_EIA30"]:
        sub=counties[counties[metric].notna()].copy()
        idx=sub.index.to_numpy()
        As=A[np.ix_(idx,idx)]
        rs=As.sum(axis=1)
        Ws=np.divide(As,rs[:,None],out=np.zeros_like(As),where=rs[:,None]>0)
        I,z,p=global_moran_permutation(sub[metric].to_numpy(),Ws)
        Ii,lp,quad=local_moran_permutation(sub[metric].to_numpy(),Ws)
        counts=pd.Series(quad).value_counts()
        summaries.append([metric,len(sub),I,z,p,int(counts.get("HH",0)),int(counts.get("LL",0)),
                          int(counts.get("HL",0)),int(counts.get("LH",0)),int(counts.get("NS",0))])
        loc=sub[["county_fips","county",metric]].copy()
        loc["local_I"]=Ii; loc["pseudo_p"]=lp; loc["cluster"]=quad; loc["metric"]=metric
        locals_all.append(loc)
    return (
        pd.DataFrame(summaries,columns=["metric","N","Moran_I","permutation_z","pseudo_p","HH","LL","HL","LH","NS"]),
        pd.concat(locals_all,ignore_index=True)
    )

def build_tables(tracts, counties):
    table2 = pd.DataFrame([
        ["Tract EJBI","Tract",tracts["EJBI"].notna().sum(),tracts["EJBI"].mean(),tracts["EJBI"].std(),tracts["EJBI"].min(),tracts["EJBI"].max()],
        ["County EJBI","County",counties["EJBI"].notna().sum(),counties["EJBI"].mean(),counties["EJBI"].std(),counties["EJBI"].min(),counties["EJBI"].max()],
        ["Primary OBI (EAGLE-I/MCC)","County",counties["OBI_MCC"].notna().sum(),counties["OBI_MCC"].mean(),counties["OBI_MCC"].std(),counties["OBI_MCC"].min(),counties["OBI_MCC"].max()],
        ["Climate Stress Index","County",counties["Climate_Stress"].notna().sum(),counties["Climate_Stress"].mean(),counties["Climate_Stress"].std(),counties["Climate_Stress"].min(),counties["Climate_Stress"].max()],
    ], columns=["Metric","Scale","N","Mean","SD","Min","Max"])

    rows = []
    valid = tracts[tracts["EJBI"].notna()]
    for th in [0.50,0.60,0.70,0.75]:
        tn = int((valid["EJBI"] >= th).sum())
        cn = int((counties["EJBI"] >= th).sum())
        rows.append([th,tn,100*tn/len(valid),cn,100*cn/len(counties)])
    table3 = pd.DataFrame(rows, columns=[
        "Numeric_EJBI_threshold","High_EJBI_tracts","Pct_valid_tracts",
        "High_EJBI_counties","Pct_counties"
    ])

    tract_var = valid["EJBI"].var()
    county_var = counties["EJBI"].var()
    table4 = pd.DataFrame([
        ["Tract","Strict numeric EJBI",len(valid),valid["EJBI"].mean(),valid["EJBI"].std(),tract_var,100.0,0.0],
        ["County","Population-weighted mean of tract numeric EJBI",len(counties),counties["EJBI"].mean(),counties["EJBI"].std(),county_var,100*county_var/tract_var,100*(1-county_var/tract_var)],
    ], columns=["Scale","Construction","N","Mean","SD","Variance","Variance_retained_pct","Variance_suppressed_pct"])

    table5 = pd.DataFrame([
        correlation_row(counties,"EJBI","OBI_MCC"),
        correlation_row(counties,"EJBI","Climate_Stress"),
        correlation_row(counties,"OBI_MCC","Climate_Stress"),
    ])

    hi = counties.loc[counties["EJBI"] >= COUNTY_HIGH_EJBI_THRESHOLD, "OBI_MCC"].dropna()
    lo = counties.loc[counties["EJBI"] < COUNTY_HIGH_EJBI_THRESHOLD, "OBI_MCC"].dropna()
    t,p = stats.ttest_ind(hi,lo,equal_var=False)
    table6 = pd.DataFrame([
        ["High-EJBI counties (>=0.60)",len(hi),hi.mean(),hi.std(),t,p],
        ["Other counties (<0.60)",len(lo),lo.mean(),lo.std(),np.nan,np.nan],
    ], columns=["Group","N","Mean_primary_OBI","SD_primary_OBI","Welch_t","Welch_p"])

    return table2,table3,table4,table5,table6


def save_figures(tracts, counties, tables):
    """SEGDA v7.4 Visual-QA release. Analytical calculations remain unchanged."""
    from matplotlib.patches import Patch
    from matplotlib.lines import Line2D
    from matplotlib.colors import Normalize
    from matplotlib.cm import ScalarMappable

    PUB = FIG / "publication"
    PREVIEW = FIG / "preview_300dpi"
    PUB.mkdir(parents=True, exist_ok=True)
    PREVIEW.mkdir(parents=True, exist_ok=True)
    layout_qa_rows = []

    def _layout_qa(fig, stem):
        """Detect text/legend clipping and suptitle/title collisions after draw."""
        fig.canvas.draw()
        renderer = fig.canvas.get_renderer()
        fb = fig.bbox
        clipped_text = 0
        clipped_legends = 0
        title_collisions = 0

        for obj in fig.findobj(match=lambda a: isinstance(a, Text)):
            if not obj.get_visible() or not str(obj.get_text()).strip():
                continue
            try:
                bb = obj.get_window_extent(renderer=renderer)
            except Exception:
                continue
            # Figure footers intentionally sit close to the lower canvas edge and
            # are exported with bbox_inches="tight". Treat vertical descender bleed
            # as intentional, but still detect horizontal overflow.
            try:
                is_footer = (obj.get_transform() == fig.transFigure and obj.get_position()[1] <= 0.03)
            except Exception:
                is_footer = False

            tol = 10  # pixels: antialiasing, tick-label descenders, tight-layout edge tolerance
            if is_footer:
                out_of_bounds = (bb.x0 < fb.x0-tol or bb.x1 > fb.x1+tol)
            else:
                out_of_bounds = (
                    bb.x0 < fb.x0-tol or bb.y0 < fb.y0-tol
                    or bb.x1 > fb.x1+tol or bb.y1 > fb.y1+tol
                )
            if out_of_bounds:
                clipped_text += 1

        for axq in fig.axes:
            lg = axq.get_legend()
            if lg is not None and lg.get_visible():
                try:
                    bb = lg.get_window_extent(renderer=renderer)
                    tol = 10
                    if bb.x0 < fb.x0-tol or bb.y0 < fb.y0-tol or bb.x1 > fb.x1+tol or bb.y1 > fb.y1+tol:
                        clipped_legends += 1
                except Exception:
                    pass

        st = getattr(fig, "_suptitle", None)
        if st is not None and st.get_visible():
            try:
                sb = st.get_window_extent(renderer=renderer)
                for axq in fig.axes:
                    ttl = axq.title
                    if ttl.get_visible() and str(ttl.get_text()).strip():
                        tb = ttl.get_window_extent(renderer=renderer)
                        if sb.overlaps(tb):
                            title_collisions += 1
            except Exception:
                pass

        # Figures are exported with bbox_inches="tight", so text that extends a few
        # pixels beyond the nominal canvas is expanded into the saved file rather than
        # clipped. Keep those counts as warnings, but fail layout QA only for legends
        # outside the canvas or actual title/title collisions.
        layout_qa_rows.append({
            "figure": stem,
            "canvas_text_overflow_warnings": clipped_text,
            "clipped_legends": clipped_legends,
            "suptitle_title_collisions": title_collisions,
            "tight_bbox_export": True,
            "layout_pass": (clipped_legends==0 and title_collisions==0)
        })

    def save_pub(fig, stem):
        _layout_qa(fig, stem)
        fig.savefig(PUB/f"{stem}.pdf", bbox_inches="tight")
        fig.savefig(PUB/f"{stem}.svg", bbox_inches="tight")
        fig.savefig(PUB/f"{stem}.png", dpi=600, bbox_inches="tight")
        fig.savefig(PREVIEW/f"{stem}_300dpi.png", dpi=300, bbox_inches="tight")
        plt.close(fig)

    def footer(fig, txt, width=112):
        """Publication-safe footer: wrap long notes so no text runs outside the canvas."""
        import textwrap as _tw
        wrapped = _tw.fill(str(txt), width=width, break_long_words=False, break_on_hyphens=False)
        fig.text(.02,.012,wrapped,ha="left",va="bottom",fontsize=6.6,linespacing=1.12)

    def north(ax):
        ax.annotate("N",xy=(.965,.94),xytext=(.965,.84),xycoords="axes fraction",
                    ha="center",fontsize=10,fontweight="bold",
                    arrowprops=dict(arrowstyle="-|>",lw=1.1))

    def info_panel(ax, heading, metrics, symbols=None, note=None):
        ax.axis("off")
        y=.96
        ax.text(.02,y,heading,va="top",fontsize=11,fontweight="bold"); y-=.08
        for line in metrics:
            ax.text(.02,y,line,va="top",fontsize=9); y-=.055
        if symbols:
            y-=.025
            ax.text(.02,y,"Legend",va="top",fontsize=10,fontweight="bold"); y-=.065
            handles=[h for h,_ in symbols]; labels=[lab for _,lab in symbols]
            dense = len(symbols) >= 6
            ax.legend(handles=handles,labels=labels,loc="upper left",
                      bbox_to_anchor=(0,y),borderaxespad=0,frameon=False,
                      fontsize=(7.2 if dense else 8.3),
                      handlelength=2.0,labelspacing=(.38 if dense else .65))
        if note:
            import textwrap as _tw
            wrapped=_tw.fill(note,width=38)
            ax.text(.02,.035,wrapped,va="bottom",fontsize=7.4,
                    bbox=dict(boxstyle="round,pad=.32",alpha=.07))

    def map_layout(title):
        fig=plt.figure(figsize=(10.5,8.0),constrained_layout=False)
        gs=fig.add_gridspec(2,2,width_ratios=[3.4,1.35],height_ratios=[18,1],
                            left=.035,right=.985,top=.91,bottom=.08,wspace=.06,hspace=.08)
        ax=fig.add_subplot(gs[0,0]); info=fig.add_subplot(gs[0,1]); cax=fig.add_subplot(gs[1,0])
        fig.suptitle(title,fontsize=15,y=.965)
        ax.set_axis_off(); info.set_axis_off()
        return fig,ax,info,cax

    def colorbar(fig,cax,label,vmin=0,vmax=1):
        sm=ScalarMappable(norm=Normalize(vmin=vmin,vmax=vmax),cmap="viridis")
        sm.set_array([])
        cb=fig.colorbar(sm,cax=cax,orientation="horizontal")
        cb.set_label(label,fontsize=9); cb.ax.tick_params(labelsize=8)

    def regression_ci(x,y,grid):
        x=np.asarray(x,float); y=np.asarray(y,float); n=len(x)
        slope,intercept=np.polyfit(x,y,1)
        pred=intercept+slope*grid
        resid=y-(intercept+slope*x)
        s_err=np.sqrt(np.sum(resid**2)/(n-2))
        xm=x.mean(); ssx=np.sum((x-xm)**2); tcrit=stats.t.ppf(.975,n-2)
        se=s_err*np.sqrt(1/n+(grid-xm)**2/ssx)
        return pred,pred-tcrit*se,pred+tcrit*se

    def bootstrap_r(df,x,y,nboot=3000,seed=42):
        z=df[[x,y]].dropna().reset_index(drop=True)
        r,p=stats.pearsonr(z[x],z[y]); rng=np.random.default_rng(seed); vals=[]
        for _ in range(nboot):
            idx=rng.integers(0,len(z),len(z)); b=z.iloc[idx]
            if b[x].nunique()>1 and b[y].nunique()>1:
                vals.append(stats.pearsonr(b[x],b[y])[0])
        lo,hi=np.quantile(vals,[.025,.975])
        return len(z),r,p,lo,hi

    valid=tracts[tracts["EJBI"].notna()].copy()
    high_t=valid[valid["EJBI"]>=TRACT_HIGH_EJBI_THRESHOLD].copy()
    high_c=counties[counties["EJBI"]>=COUNTY_HIGH_EJBI_THRESHOLD].copy()
    incomplete=tracts[tracts["EJBI"].isna()].copy()
    tract_var=valid["EJBI"].var(); county_var=counties["EJBI"].var()
    suppression=100*(1-county_var/tract_var)

    # 1 Framework: short labels, no arrows through text.
    fig,ax=plt.subplots(figsize=(10,6.2)); ax.axis("off"); ax.set_xlim(0,10); ax.set_ylim(0,7)
    ax.set_title("SEGDA Analytical Framework",fontsize=16,pad=12)
    boxes=[(1.5,5.5,"ENVIRONMENTAL\nCES + SVI"),(1.5,3.5,"GRID\nEAGLE-I + MCC"),
           (1.5,1.5,"CLIMATE\nFEMA NRI"),(5,5.5,"EJBI\nTract → County"),
           (5,3.5,"Primary OBI\nCOH / MCC"),(5,1.5,"Climate Stress\n7 hazards"),
           (8.3,4.4,"INTEGRATED ANALYSIS\nMAUP • Correlation • Spatial"),
           (8.3,2.1,"EIA-861\nSensitivity only")]
    for x,y,t in boxes:
        ax.text(x,y,t,ha="center",va="center",fontsize=10.5,
                bbox=dict(boxstyle="round,pad=.55",alpha=.10))
    for a,b in [((2.5,5.5),(4,5.5)),((2.5,3.5),(4,3.5)),((2.5,1.5),(4,1.5)),
                ((6,5.35),(7.1,4.65)),((6,3.55),(7.1,4.25)),((6,1.7),(7.1,3.9)),
                ((6,3.25),(7.1,2.35))]:
        ax.annotate("",xy=b,xytext=a,arrowprops=dict(arrowstyle="->",lw=1.3))
    footer(fig,"Primary OBI = EAGLE-I/MCC. EIA-861 is sensitivity-only. High-EJBI is study-defined, not an official SB 535 DAC designation.")
    save_pub(fig,"Fig01_SEGDA_analytical_framework")

    # 2 Tract EJBI.
    fig,ax,info,cax=map_layout("Tract-Level Environmental Justice Burden Index")
    tracts.plot(column="EJBI",ax=ax,vmin=0,vmax=1,cmap="viridis",linewidth=0)
    if len(incomplete): incomplete.plot(ax=ax,facecolor="none",edgecolor=".55",hatch="////",linewidth=.15)
    high_t.boundary.plot(ax=ax,linewidth=.22,edgecolor="black")
    north(ax); colorbar(fig,cax,"Numeric EJBI (0–1)")
    info_panel(info,"EJBI coverage",
        [f"Tract geometries: {len(tracts):,}",f"Valid strict EJBI: {len(valid):,}",
         f"Incomplete EJBI: {len(incomplete):,}",f"High-EJBI: {len(high_t):,} ({100*len(high_t)/len(valid):.1f}%)",
         "Threshold: EJBI ≥ 0.75"],
        [(Line2D([0],[0],lw=2,color="black"),"High-EJBI tract boundary"),
         (Patch(facecolor="none",edgecolor=".5",hatch="////"),"Incomplete EJBI")],
        "Incomplete EJBI is not zero. Strict EJBI requires SVI, CES overall percentile, and Pollution Burden; tracts missing ≥1 component are excluded.")
    footer(fig,"Strict three-component EJBI; missing values are excluded rather than imputed as zero.")
    save_pub(fig,"Fig02_tract_EJBI_map")

    # 3 County EJBI.
    fig,ax,info,cax=map_layout("County-Level EJBI (Population-Weighted)")
    counties.plot(column="EJBI",ax=ax,vmin=0,vmax=1,cmap="viridis")
    counties.boundary.plot(ax=ax,linewidth=.45,edgecolor=".25")
    high_c.boundary.plot(ax=ax,linewidth=1.8,edgecolor="black",linestyle="--")
    north(ax); colorbar(fig,cax,"Population-weighted county EJBI (0–1)")
    info_panel(info,"County EJBI",
        ["Complete counties: 58/58",f"Mean: {counties['EJBI'].mean():.3f}",
         f"Range: {counties['EJBI'].min():.3f}–{counties['EJBI'].max():.3f}",
         f"High-EJBI counties: {len(high_c)}/58"],
        [(Line2D([0],[0],lw=2,ls="--",color="black"),"High-EJBI county (≥0.60)")],
        "County EJBI is the population-weighted mean of valid tract EJBI scores.")
    footer(fig,"Continuous EJBI scale fixed at 0–1 for direct interpretation.")
    save_pub(fig,"Fig03_county_EJBI_map")

    # 4 MAUP compact transition.
    fig,ax=plt.subplots(figsize=(8.8,4.7)); ax.axis("off"); ax.set_xlim(0,10); ax.set_ylim(0,5)
    ax.set_title("Scale-Consistent MAUP: EJBI Information Loss",fontsize=15,pad=10)
    ax.text(2,2.7,f"TRACT SCALE\nVariance {tract_var:.5f}\nn = {len(valid):,}",ha="center",va="center",fontsize=12,
            bbox=dict(boxstyle="round,pad=.65",alpha=.1))
    ax.text(8,2.7,f"COUNTY SCALE\nVariance {county_var:.5f}\nn = 58",ha="center",va="center",fontsize=12,
            bbox=dict(boxstyle="round,pad=.65",alpha=.1))
    ax.annotate("",xy=(6.7,2.7),xytext=(3.3,2.7),arrowprops=dict(arrowstyle="->",lw=2))
    ax.text(5,3.55,f"−{suppression:.2f}% variance",ha="center",fontsize=15,fontweight="bold")
    ax.text(5,1.65,f"{100-suppression:.2f}% retained",ha="center",fontsize=11)
    footer(fig,"Same numeric EJBI construction is compared at tract and county scales.")
    save_pub(fig,"Fig04_MAUP_information_retention")

    # 5 Hidden tracts: map + ranking, no box on map.
    cc=counties[["county_fips","county","EJBI"]].rename(columns={"EJBI":"county_EJBI"})
    h=tracts.merge(cc,on="county_fips",how="left")
    h=h[(h["EJBI"]>=TRACT_HIGH_EJBI_THRESHOLD)&(h["county_EJBI"]<COUNTY_HIGH_EJBI_THRESHOLD)].copy()
    ranks=h.groupby("county").size().sort_values(ascending=False)
    fig=plt.figure(figsize=(11,7.8)); gs=fig.add_gridspec(1,2,width_ratios=[2.7,1.4],left=.04,right=.98,top=.91,bottom=.08,wspace=.12)
    ax=fig.add_subplot(gs[0,0]); side=fig.add_subplot(gs[0,1])
    tracts.boundary.plot(ax=ax,linewidth=.05,edgecolor=".75"); h.plot(ax=ax,alpha=.8)
    counties.boundary.plot(ax=ax,linewidth=.5,edgecolor=".25"); ax.axis("off"); north(ax)
    side.barh(ranks.head(10).index[::-1],ranks.head(10).values[::-1])
    side.set_xlabel("Masked High-EJBI tracts"); side.grid(axis="x",alpha=.2)
    side.text(.5,1.015,"Top counties",transform=side.transAxes,ha="center",va="bottom",
              fontsize=10,fontweight="bold")
    fig.suptitle("High-EJBI Tracts Masked by County-Level Aggregation",fontsize=14,y=.985)
    fig.text(.5,.945,"431 masked tracts  |  25.5% of all High-EJBI tracts",
             ha="center",va="top",fontsize=9.2)
    footer(fig,"Masked = tract EJBI ≥0.75 located within a county whose population-weighted EJBI is <0.60.")
    save_pub(fig,"Fig05_hidden_High_EJBI_tracts")

    # 6 variance bars supplementary.
    fig,ax=plt.subplots(figsize=(7,5.2)); vals=[tract_var,county_var]; bars=ax.bar(["Tract","County"],vals)
    ax.set_ylim(0,max(vals)*1.28); ax.set_ylabel("EJBI variance"); ax.set_title("EJBI Variance by Geographic Scale",fontsize=14)
    ax.grid(axis="y",alpha=.2)
    for b,v in zip(bars,vals): ax.text(b.get_x()+b.get_width()/2,v+max(vals)*.035,f"{v:.5f}",ha="center")
    ax.annotate(f"{suppression:.2f}% suppressed",xy=(1,county_var),xytext=(.5,max(vals)*.77),ha="center",
                arrowprops=dict(arrowstyle="->"))
    footer(fig,f"County aggregation retains {100-suppression:.2f}% of tract-scale EJBI variance.")
    save_pub(fig,"Fig06_MAUP_variance_bars")

    # 7 OBI map with external missing-data explanation and ranked list.
    fig,ax,info,cax=map_layout("Primary Outage Burden Index (EAGLE-I / MCC)")
    counties.plot(column="OBI_MCC",ax=ax,vmin=0,vmax=1,cmap="viridis")
    miss=counties[counties["OBI_MCC"].isna()]
    if len(miss): miss.plot(ax=ax,facecolor="none",edgecolor=".45",hatch="xxxx",linewidth=.7)
    counties.boundary.plot(ax=ax,linewidth=.45,edgecolor=".25"); north(ax); colorbar(fig,cax,"Normalized primary OBI (0–1)")
    top=counties.dropna(subset=["OBI_MCC"]).nlargest(5,"OBI_MCC")
    metrics=[f"Complete OBI: {counties['OBI_MCC'].notna().sum()}/58",f"Unavailable: {len(miss)}",
             f"Mean: {counties['OBI_MCC'].mean():.3f}",f"EAGLE-I episodes: {int(counties['reconstructed_episodes'].sum()):,}",
             "","Highest OBI counties:"]+[f"{r.county}: {r.OBI_MCC:.3f}" for _,r in top.iterrows()]
    miss_names=", ".join(miss["county"].tolist()) if len(miss) else "None"
    info_panel(info,"Primary OBI",metrics,
        [(Patch(facecolor="none",edgecolor=".45",hatch="xxxx"),"Primary OBI unavailable")],
        f"Unavailable counties: {miss_names}. Missing/unavailable values are not treated as zero. Primary OBI requires reconstructed outage exposure and an MCC denominator.")
    footer(fig,"Primary OBI = normalized reconstructed EAGLE-I customer-outage-hours per modeled county customer.", width=140)
    save_pub(fig,"Fig07_primary_OBI_map")

    # 8 Climate map.
    fig,ax,info,cax=map_layout("County-Level Climate Stress Index")
    counties.plot(column="Climate_Stress",ax=ax,vmin=0,vmax=1,cmap="viridis")
    counties.boundary.plot(ax=ax,linewidth=.45,edgecolor=".25"); north(ax); colorbar(fig,cax,"Climate Stress Index (0–1)")
    info_panel(info,"Climate Stress",
        ["Complete counties: 58/58",f"Mean: {counties['Climate_Stress'].mean():.3f}",
         f"Range: {counties['Climate_Stress'].min():.3f}–{counties['Climate_Stress'].max():.3f}",
         "","Components:","Drought • Heat • Wildfire","Riverine flood • Earthquake","Strong wind • Tornado"],
        note="Unweighted mean of seven individually min–max-normalized FEMA NRI risk scores.")
    footer(fig,"No county is missing the Climate Stress index in the locked analysis.")
    save_pub(fig,"Fig08_climate_stress_map")

    # 9 Scatter: stats strip, external legend, constrained y.
    z=counties[["county","EJBI","OBI_MCC"]].dropna().copy(); z["High"]=z["EJBI"]>=COUNTY_HIGH_EJBI_THRESHOLD
    n,r,p,lo,hi=bootstrap_r(z,"EJBI","OBI_MCC")
    fig=plt.figure(figsize=(8.6,6.3)); gs=fig.add_gridspec(2,2,height_ratios=[.55,5],width_ratios=[5,1.45],hspace=.04,wspace=.08)
    stat=fig.add_subplot(gs[0,:]); ax=fig.add_subplot(gs[1,0]); leg=fig.add_subplot(gs[1,1]); stat.axis("off"); leg.axis("off")
    stat.text(.5,.55,f"Pearson r = {r:.3f}   |   95% bootstrap CI {lo:.3f} to {hi:.3f}   |   p = {p:.5f}   |   n = {n}",
              ha="center",va="center",fontsize=10.5,fontweight="medium")
    a=z[~z.High]; b=z[z.High]
    ax.scatter(a.EJBI,a.OBI_MCC,marker="o",s=42,label="Other county"); ax.scatter(b.EJBI,b.OBI_MCC,marker="D",s=48,label="High-EJBI county")
    grid=np.linspace(z.EJBI.min(),z.EJBI.max(),150); pred,cl,ch=regression_ci(z.EJBI,z.OBI_MCC,grid)
    ax.plot(grid,pred,lw=1.7,label="Linear fit"); ax.fill_between(grid,cl,ch,alpha=.15,label="95% confidence band")
    ax.axvline(.60,ls="--",lw=1); ax.text(.602,1.01,"EJBI = 0.60",fontsize=8,va="top")
    ax.set_ylim(0,1.05); ax.set_xlabel("County EJBI"); ax.set_ylabel("Primary OBI"); ax.grid(alpha=.2)
    leg.legend(handles=[Line2D([0],[0],marker="o",ls="None",label="Other county"),
                        Line2D([0],[0],marker="D",ls="None",label="High-EJBI county"),
                        Line2D([0],[0],lw=1.7,label="Linear fit"),
                        Patch(alpha=.15,label="95% CI band"),
                        Line2D([0],[0],ls="--",label="EJBI threshold")],
               loc="upper left",frameon=False,fontsize=8.5)
    fig.suptitle("Environmental Justice Burden vs. Primary Outage Burden",fontsize=15,y=.98)
    footer(fig,"Displayed OBI range is constrained to the observed 0–1 index scale; linear regression itself is unconstrained.")
    save_pub(fig,"Fig09_EJBI_vs_primary_OBI")

    # 10 Three-way relationships: dedicated title band; per-panel statistics stay inside axes.
    pairs=[("EJBI","Climate_Stress","EJBI","Climate Stress"),
           ("EJBI","OBI_MCC","EJBI","Primary OBI"),
           ("Climate_Stress","OBI_MCC","Climate Stress","Primary OBI")]
    fig=plt.figure(figsize=(12,5.2))
    gs=fig.add_gridspec(2,3,height_ratios=[.45,4.8],left=.055,right=.985,top=.91,bottom=.14,
                        hspace=.04,wspace=.30)
    head=fig.add_subplot(gs[0,:]); head.axis("off")
    head.text(.5,.55,"County Relationships Among EJBI, Climate Stress, and Grid Disruption",
              ha="center",va="center",fontsize=14,fontweight="medium")
    axes=[fig.add_subplot(gs[1,i]) for i in range(3)]
    for ax,(x,y,xlab,ylab) in zip(axes,pairs):
        q=counties[[x,y]].dropna(); rr,pp=stats.pearsonr(q[x],q[y])
        ax.scatter(q[x],q[y],s=24)
        grid=np.linspace(q[x].min(),q[x].max(),100); pred,cl,ch=regression_ci(q[x],q[y],grid)
        ax.plot(grid,pred,lw=1.4); ax.fill_between(grid,cl,ch,alpha=.13)
        ax.set_xlabel(xlab,fontsize=9); ax.set_ylabel(ylab,fontsize=9); ax.grid(alpha=.18)
        ax.text(.03,.97,f"r = {rr:+.3f}\np = {pp:.4g}",transform=ax.transAxes,
                ha="left",va="top",fontsize=8.5,
                bbox=dict(boxstyle="round,pad=.28",facecolor="white",alpha=.85,edgecolor=".7"))
    footer(fig,"Each panel shows the observed county relationship, linear fit, and 95% confidence band.")
    save_pub(fig,"Fig10_three_way_relationship")

    # 11 Robustness forest plot: plot and numerical results are separate panels.
    specs=[("Primary EAGLE-I/MCC","OBI_MCC","o"),("Population-normalized","OBI_POP","o"),
           ("Exclude 34-h ceiling","OBI_MCC_EXCL34","o"),("80/20 EAGLE-I/EIA","OBI_EIA20","D"),
           ("70/30 EAGLE-I/EIA","OBI_EIA30","D"),("50/50 EAGLE-I/EIA","OBI_EIA50","D")]
    vals=[]
    for label,col,m in specs:
        nn,rr,pp,ll,hh=bootstrap_r(counties,"EJBI",col); vals.append((label,m,nn,rr,ll,hh))
    fig=plt.figure(figsize=(10.8,5.8))
    gs=fig.add_gridspec(1,2,width_ratios=[3.0,1.75],left=.22,right=.985,top=.88,bottom=.16,wspace=.07)
    ax=fig.add_subplot(gs[0,0]); tab=fig.add_subplot(gs[0,1]); tab.axis("off")
    ys=np.arange(len(vals))
    for y,(label,m,nn,rr,ll,hh) in zip(ys,vals):
        ax.errorbar(rr,y,xerr=[[rr-ll],[hh-rr]],fmt=m,capsize=3,markersize=7)
    ax.axvline(0,ls="--",lw=1)
    ax.set_xlim(-.85,.08)
    ax.set_yticks(ys,[v[0] for v in vals],fontsize=9)
    ax.invert_yaxis(); ax.set_xlabel("Pearson correlation with county EJBI",fontsize=9)
    ax.grid(axis="x",alpha=.2)
    tab.text(.02,.98,"Estimate (95% bootstrap CI)     n",va="top",fontsize=9,fontweight="bold")
    y0=.88
    for label,m,nn,rr,ll,hh in vals:
        tab.text(.02,y0,f"{rr:.3f}  [{ll:.3f}, {hh:.3f}]     {nn}",va="center",fontsize=8.5)
        y0-=.145
    tab.legend(handles=[Line2D([0],[0],marker="o",ls="None",label="EAGLE-I-based"),
                        Line2D([0],[0],marker="D",ls="None",label="EIA-inclusive")],
               loc="lower left",frameon=False,fontsize=8)
    fig.suptitle("Robustness of the EJBI–Outage Relationship Across OBI Specifications",
                 fontsize=13.5,y=.96)
    footer(fig,"Horizontal bars are 95% bootstrap confidence intervals; EIA-inclusive models are sensitivity analyses.")
    save_pub(fig,"Fig11_OBI_sensitivity_forest")

    # 12-13 LISA: external panel and explicit missing category.
    spatial,lisa=spatial_diagnostics(counties)
    hatch={"HH":"////","LL":"\\\\\\\\","HL":"xxxx","LH":"....","NS":""}
    names={"HH":"High–High","LL":"Low–Low","HL":"High–Low","LH":"Low–High","NS":"Not significant"}
    for metric,stem,title in [("EJBI","Fig12_LISA_EJBI","EJBI Local Spatial Clusters"),
                              ("OBI_MCC","Fig13_LISA_primary_OBI","Primary OBI Local Spatial Clusters")]:
        loc=lisa[lisa.metric==metric][["county_fips","cluster","pseudo_p"]]
        gm=counties.merge(loc,on="county_fips",how="left"); missing=gm[gm[metric].isna()]
        fig=plt.figure(figsize=(10.3,7.8)); gs=fig.add_gridspec(1,2,width_ratios=[3.5,1.35],left=.04,right=.98,top=.91,bottom=.07,wspace=.06)
        ax=fig.add_subplot(gs[0,0]); info=fig.add_subplot(gs[0,1])
        gm.boundary.plot(ax=ax,linewidth=.45,edgecolor=".3")
        for k in ["HH","LL","HL","LH","NS"]:
            part=gm[gm.cluster==k]
            if len(part): part.plot(ax=ax,hatch=hatch[k],alpha=.55)
        if len(missing): missing.plot(ax=ax,facecolor="none",edgecolor=".4",hatch="++++",linewidth=.8)
        ax.axis("off"); north(ax)
        row=spatial[spatial.metric==metric].iloc[0]
        symbols=[(Patch(hatch=hatch[k]),names[k]) for k in ["HH","LL","HL","LH","NS"]]
        if len(missing): symbols.append((Patch(facecolor="none",hatch="++++"),"Metric unavailable"))
        lisa_metrics = [
            f"Moran's I: {row.Moran_I:.3f}",
            f"Permutation p: {row.pseudo_p:.3f}",
            f"HH: {int(row.HH)}",
            f"LL: {int(row.LL)}",
            f"HL: {int(row.HL)}",
            f"LH: {int(row.LH)}",
            f"Not significant: {int(row.NS)}",
        ]
        if len(missing):
            lisa_metrics.append(f"Unavailable: {len(missing)}")
            lisa_note = (
                "Not significant means the county entered the LISA analysis but did not meet p<0.05. "
                "Unavailable means the metric itself could not be computed."
            )
            lisa_footer = (
                "Queen contiguity; 999 permutations; local significance threshold p < 0.05. "
                "Metric unavailable is visually distinct from non-significance."
            )
        else:
            lisa_note = (
                "Not significant means the county entered the LISA analysis but did not meet p<0.05."
            )
            lisa_footer = "Queen contiguity; 999 permutations; local significance threshold p < 0.05."

        info_panel(info,"Spatial statistics",lisa_metrics,symbols,lisa_note)
        fig.suptitle(title,fontsize=15,y=.96)
        footer(fig,lisa_footer)
        save_pub(fig,stem)

    # 14 SVI concordance: stats strip, quadrant labels.
    sp=OUT/"v7_SVI_EJBI_concordance.csv"
    if sp.exists():
        sc=pd.read_csv(sp).dropna(subset=["EJBI","SVI_county"]).copy()
        n,r,p,lo,hi=bootstrap_r(sc,"SVI_county","EJBI"); agreement=100*sc.concordant.mean()
        fig=plt.figure(figsize=(8.4,6.2)); gs=fig.add_gridspec(2,1,height_ratios=[.55,5],hspace=.04)
        stat=fig.add_subplot(gs[0]); ax=fig.add_subplot(gs[1]); stat.axis("off")
        stat.text(.5,.55,f"r = {r:.3f}   |   95% CI {lo:.3f} to {hi:.3f}   |   p < .001   |   threshold agreement = {agreement:.1f}%",
                  ha="center",fontsize=10.2,fontweight="medium")
        both=sc[(sc.EJBI_high)&(sc.SVI_high)]; other=sc.drop(both.index)
        ax.scatter(other.SVI_county,other.EJBI,marker="o",s=38,label="Other classification")
        ax.scatter(both.SVI_county,both.EJBI,marker="D",s=46,label="High on both")
        grid=np.linspace(sc.SVI_county.min(),sc.SVI_county.max(),120); pred,cl,ch=regression_ci(sc.SVI_county,sc.EJBI,grid)
        ax.plot(grid,pred,lw=1.5); ax.fill_between(grid,cl,ch,alpha=.13)
        ax.axvline(.75,ls="--",lw=1); ax.axhline(.60,ls=":",lw=1)
        ax.text(.78,.72,"Both high",fontsize=8); ax.text(.78,.28,"SVI high only",fontsize=8)
        ax.text(.16,.72,"EJBI high only",fontsize=8); ax.text(.16,.28,"Both below",fontsize=8)
        ax.set_xlabel("County SVI (RPL_THEMES)"); ax.set_ylabel("County EJBI"); ax.grid(alpha=.18)
        ax.legend(loc="lower right",frameon=False,fontsize=8)
        fig.suptitle("County SVI–EJBI Concordance",fontsize=15,y=.98)
        footer(fig,"Threshold comparison: SVI ≥0.75 versus study-defined county EJBI ≥0.60.")
        save_pub(fig,"Fig14_SVI_EJBI_concordance")

    # 15 EIA coverage: discrete categories and no colorbar.
    if "years_with_ge80_coverage" in counties.columns:
        vals=counties["years_with_ge80_coverage"]
        fig=plt.figure(figsize=(10.3,7.8)); gs=fig.add_gridspec(1,2,width_ratios=[3.5,1.35],left=.04,right=.98,top=.91,bottom=.07,wspace=.06)
        ax=fig.add_subplot(gs[0,0]); info=fig.add_subplot(gs[0,1])
        cats=sorted([int(x) for x in vals.dropna().unique()],reverse=True)
        hatch_seq=["","////","\\\\\\\\","....","xxxx","++++","oo"]
        symbols=[]
        for i,k in enumerate(cats):
            part=counties[vals==k]
            part.plot(ax=ax,hatch=hatch_seq[i%len(hatch_seq)],alpha=.55)
            if k == 0:
                label = "0 years meeting ≥80% coverage"
            elif k == 1:
                label = "1 year meeting ≥80% coverage"
            else:
                label = f"{k} years meeting ≥80% coverage"
            symbols.append((Patch(hatch=hatch_seq[i%len(hatch_seq)]),label))

        no_match=counties[vals.isna()]
        if len(no_match):
            no_match.plot(ax=ax,facecolor="none",edgecolor=".4",hatch="++++")
            symbols.append((Patch(facecolor="none",hatch="++++"),"No matched EIA-861 coverage record"))

        eligible=counties[vals>=4]
        eligible.boundary.plot(ax=ax,linewidth=1.7,edgecolor="black")
        counties.boundary.plot(ax=ax,linewidth=.4,edgecolor=".3")
        ax.axis("off"); north(ax)
        symbols.append((Line2D([0],[0],lw=2,color="black"),"Eligible: ≥4 years meeting coverage criterion"))

        info_panel(
            info,
            "Historical reliability coverage",
            [
                f"Eligible (≥4 years): {len(eligible)} counties",
                f"All 6 years qualify: {int((vals==6).sum())}",
                f"1–3 qualifying years: {int(((vals>=1)&(vals<4)).sum())}",
                f"0 qualifying years: {int((vals==0).sum())}",
                f"No matched EIA-861 record: {int(vals.isna().sum())}",
                "",
                "Annual criterion: ≥80% reporting coverage",
                "Historical sensitivity index: ≥4 qualifying years",
            ],
            symbols,
            (
                "A value of 0 means EIA-861 coverage records were matched, but no study year met the ≥80% "
                "reporting-coverage criterion. 'No matched EIA-861 record' means no historical coverage "
                "record was joined for that county. These are distinct data-quality states."
            ),
        )
        fig.suptitle("Historical EIA-861 Reliability Coverage, 2018–2023",fontsize=15,y=.96)
        footer(
            fig,
            "EIA-861 is a sensitivity branch only. Counties with <4 qualifying years are excluded from "
            "the historical sensitivity index; no county is assigned zero reliability because of missing coverage."
        )
        save_pub(fig,"Fig15_EIA861_historical_coverage")

    # 16 Distribution: threshold is directly labeled inside the plotting area.
    fig,ax=plt.subplots(figsize=(7.8,5.5))
    fig.subplots_adjust(top=.88,bottom=.15,left=.12,right=.97)
    x=valid.EJBI
    counts,bins,_=ax.hist(x,bins=30)
    ax.axvline(.75,ls="--",lw=1.5)
    ax.text(.755,max(counts)*.96,"High-EJBI threshold\nEJBI = 0.75",
            ha="left",va="top",fontsize=8.5,
            bbox=dict(boxstyle="round,pad=.25",facecolor="white",alpha=.85,edgecolor="none"))
    ax.set_ylim(0,max(counts)*1.08)
    ax.set_xlabel("Numeric EJBI"); ax.set_ylabel("Tract count"); ax.grid(axis="y",alpha=.2)
    ax.set_title("Distribution of Strict Three-Component Tract EJBI",fontsize=13.5,pad=10)
    ax.text(.03,.94,f"n = {len(x):,}\nMean = {x.mean():.3f}\nSD = {x.std():.3f}\nHigh-EJBI = {len(high_t):,} ({100*len(high_t)/len(x):.1f}%)",
            transform=ax.transAxes,va="top",fontsize=8.8,
            bbox=dict(boxstyle="round,pad=.35",facecolor="white",alpha=.82,edgecolor=".75"))
    footer(fig,"The 0.75 line is a study-defined numeric threshold, not an official California SB 535 DAC cutoff.")
    save_pub(fig,"Fig16_tract_EJBI_distribution")

    pd.DataFrame([
        ["Fig01","Framework","Primary"],["Fig02","Tract EJBI","Primary"],["Fig03","County EJBI","Primary"],
        ["Fig04","MAUP information loss","Primary"],["Fig05","Masked High-EJBI tracts","Primary"],
        ["Fig06","MAUP variance bars","Supplementary"],["Fig07","Primary OBI","Primary"],
        ["Fig08","Climate Stress","Primary"],["Fig09","EJBI vs OBI","Primary"],["Fig10","Three relationships","Primary"],
        ["Fig11","OBI sensitivity","Primary"],["Fig12","EJBI LISA","Primary/Supplementary"],
        ["Fig13","OBI LISA","Primary/Supplementary"],["Fig14","SVI concordance","Supplementary"],
        ["Fig15","EIA coverage","Supplementary"],["Fig16","EJBI distribution","Supplementary"]
    ],columns=["figure","title","placement"]).to_csv(OUT/"v7_6_visual_QA_figure_inventory.csv",index=False)

    pd.DataFrame(layout_qa_rows).to_csv(OUT/"v7_6_figure_layout_QA.csv",index=False)

    figure_semantic_audit = pd.DataFrame([
        {
            "figure":"Fig12_LISA_EJBI",
            "metric":"EJBI",
            "expected_unavailable":0,
            "rule":"No unavailable label/note is shown when county EJBI is complete.",
            "pass": int(counties["EJBI"].isna().sum()) == 0,
        },
        {
            "figure":"Fig13_LISA_primary_OBI",
            "metric":"OBI_MCC",
            "expected_unavailable":2,
            "rule":"Unavailable primary OBI counties remain distinct from LISA non-significance.",
            "pass": int(counties["OBI_MCC"].isna().sum()) == 2,
        },
        {
            "figure":"Fig15_EIA861_historical_coverage",
            "metric":"years_with_ge80_coverage",
            "expected_unavailable":1,
            "rule":"Zero qualifying years and no matched EIA-861 coverage record are distinct states.",
            "pass": (
                "years_with_ge80_coverage" in counties.columns
                and int(counties["years_with_ge80_coverage"].isna().sum()) == 1
            ),
        },
    ])
    figure_semantic_audit.to_csv(OUT/"v7_6_figure_semantic_QA.csv",index=False)
    if not bool(figure_semantic_audit["pass"].all()):
        raise AssertionError("Figure semantic QA failed; see v7_6_figure_semantic_QA.csv")

def validate(tracts, episodes, counties, tables):
    validations = []
    def check(name, actual, expected, tol=0):
        if tol == 0:
            ok = actual == expected
        else:
            ok = abs(actual-expected) <= tol
        validations.append({"check":name,"actual":actual,"expected":expected,"tolerance":tol,"pass":bool(ok)})
        if not ok:
            raise AssertionError(f"{name}: actual={actual}, expected={expected}, tol={tol}")

    check("tract geometry count", len(tracts), EXPECTED["tract_geometry_n"])
    check("strict EJBI tract count", int(tracts["EJBI"].notna().sum()), EXPECTED["strict_ejbi_n"])
    check("High-EJBI tract count", int((tracts["EJBI"]>=TRACT_HIGH_EJBI_THRESHOLD).sum()), EXPECTED["high_ejbi_tracts"])
    check("county count", len(counties), EXPECTED["county_n"])
    check("High-EJBI county count", int((counties["EJBI"]>=COUNTY_HIGH_EJBI_THRESHOLD).sum()), EXPECTED["high_ejbi_counties"])

    suppression = float(tables[2].loc[tables[2]["Scale"]=="County","Variance_suppressed_pct"].iloc[0])
    check("MAUP suppression pct", suppression, EXPECTED["maup_suppression_pct"], 0.01)

    z = counties[["EJBI","OBI_MCC"]].dropna()
    r = stats.pearsonr(z["EJBI"],z["OBI_MCC"])[0]
    check("EJBI-OBI Pearson r", r, EXPECTED["ejbi_obi_r"], 0.002)

    z = counties[["Climate_Stress","OBI_MCC"]].dropna()
    r = stats.pearsonr(z["Climate_Stress"],z["OBI_MCC"])[0]
    check("Climate-OBI Pearson r", r, EXPECTED["climate_obi_r"], 0.002)

    z = counties[["EJBI","OBI_EIA30"]].dropna()
    r = stats.pearsonr(z["EJBI"],z["OBI_EIA30"])[0]
    check("EJBI-OBI 70/30 EIA sensitivity r", r, EXPECTED["eia30_ejbi_r"], 0.003)

    z = counties[["Climate_Stress","OBI_EIA30"]].dropna()
    r = stats.pearsonr(z["Climate_Stress"],z["OBI_EIA30"])[0]
    check("Climate-OBI 70/30 EIA sensitivity r", r, EXPECTED["eia30_climate_r"], 0.003)

    # Structural EAGLE-I assertions
    if len(episodes) != episodes[["fips","state","county","start_time","duration","min_customers","max_customers","mean_customers"]].drop_duplicates().shape[0]:
        raise AssertionError("EAGLE-I deduplication failed: duplicate underlying episode identities remain.")
    validations.append({"check":"EAGLE-I unique underlying episode identity","actual":len(episodes),"expected":"all unique","tolerance":"","pass":True})

    return pd.DataFrame(validations)

def main():
    started = datetime.now()
    print("="*78)
    print(f"SEGDA v{SCRIPT_VERSION} — AUDITED REPRODUCIBILITY RUN")
    print("="*78)

    paths = load_inputs()
    provenance = build_provenance(paths)

    tracts = build_tract_ejbi(paths)
    counties = build_county_ejbi(tracts, paths)
    episodes = clean_eaglei_episodes(paths)
    burden = build_outage_burden(episodes, paths)
    climate = build_climate(paths)
    counties = combine_metrics(counties, burden, climate)
    counties = attach_eia_historical_sensitivity(counties, paths)

    # Save analytical data before tables.
    save_csv_export(tracts.drop(columns="geometry"), "v7_tract_metrics.csv", category="data", index=False)
    save_csv_export(counties.drop(columns="geometry"), "v7_county_metrics.csv", category="data", index=False)
    save_csv_export(episodes, "v7_eaglei_clean_episodes_2018_2023.csv", category="data", index=False)

    # Annual EAGLE QA.
    annual = episodes.groupby("year").agg(
        reconstructed_episodes=("county_fips","size"),
        counties=("county_fips","nunique"),
        first_timestamp=("start_time","min"),
        last_timestamp=("start_time","max"),
        at_200_floor=("qa_min_customers_at_200","sum"),
        at_34h_ceiling=("qa_duration_at_34h","sum"),
        estimated_coh=("estimated_customer_outage_hours","sum"),
    ).reset_index()
    save_csv_export(annual, "v7_eaglei_annual_QA.csv", category="results", index=False)

    tables = build_tables(tracts, counties)
    for n, table in zip(["II","III","IV","V","VI"], tables):
        save_csv_export(table, f"v7_Table_{n}.csv", category="tables", index=False)

    # Sensitivity correlation report.
    sens = pd.DataFrame([
        correlation_row(counties,"EJBI","OBI_MCC"),
        correlation_row(counties,"EJBI","OBI_POP"),
        correlation_row(counties,"EJBI","OBI_MCC_EXCL34"),
        correlation_row(counties,"EJBI","OBI_EIA20"),
        correlation_row(counties,"EJBI","OBI_EIA30"),
        correlation_row(counties,"EJBI","OBI_EIA50"),
        correlation_row(counties,"Climate_Stress","OBI_MCC"),
        correlation_row(counties,"Climate_Stress","OBI_POP"),
        correlation_row(counties,"Climate_Stress","OBI_MCC_EXCL34"),
        correlation_row(counties,"Climate_Stress","OBI_EIA20"),
        correlation_row(counties,"Climate_Stress","OBI_EIA30"),
        correlation_row(counties,"Climate_Stress","OBI_EIA50"),
    ])
    save_csv_export(sens, "v7_OBI_sensitivity_correlations.csv", category="results", index=False)

    remaining, hidden_by_county, svi_concordance = remaining_claims_diagnostics(tracts, counties, paths)
    save_csv_export(remaining, "v7_remaining_claims_validation.csv", category="results", index=False)
    save_csv_export(hidden_by_county, "v7_hidden_High_EJBI_tracts_by_county.csv", category="results", index=False)
    save_csv_export(
        svi_concordance.drop(columns="geometry",errors="ignore"),
        "v7_SVI_EJBI_concordance.csv",
        category="results",
        index=False,
    )

    spatial, lisa = spatial_diagnostics(counties)
    save_csv_export(spatial, "v7_spatial_autocorrelation.csv", category="results", index=False)
    save_csv_export(lisa, "v7_LISA_clusters.csv", category="results", index=False)

    # Bootstrap CIs for central relationships.
    ci_rows=[]
    for x,y in [("EJBI","OBI_MCC"),("Climate_Stress","OBI_MCC"),
                ("EJBI","Climate_Stress"),("EJBI","OBI_EIA30"),
                ("Climate_Stress","OBI_EIA30")]:
        n,r,p,lo,hi=bootstrap_corr(counties,x,y)
        ci_rows.append([x,y,n,r,p,lo,hi])
    save_csv_export(
        pd.DataFrame(ci_rows,columns=["x","y","N","Pearson_r","p_value","CI_low","CI_high"]),
        "v7_bootstrap_correlation_CIs.csv",
        category="results",
        index=False,
    )

    validation = validate(tracts, episodes, counties, tables)

    # Extend validation with previously inherited paper claims.
    def add_validation(name,actual,expected,tol):
        ok=abs(float(actual)-float(expected))<=tol
        validation.loc[len(validation)]={"check":name,"actual":actual,"expected":expected,"tolerance":tol,"pass":ok}
        if not ok:
            raise AssertionError(f"{name}: actual={actual}, expected={expected}, tol={tol}")
    rem=dict(zip(remaining["metric"],remaining["value"]))
    add_validation("Hidden High-EJBI tract count",rem["hidden_high_EJBI_tracts"],EXPECTED["hidden_high_ejbi_tracts"],0)
    add_validation("SVI-EJBI Pearson r",rem["SVI_EJBI_Pearson_r"],EXPECTED["svi_ejbi_r"],0.002)
    add_validation("SVI-EJBI agreement pct",rem["SVI_EJBI_agreement_pct"],EXPECTED["svi_ejbi_agreement_pct"],0.02)
    sm=dict(zip(spatial["metric"],spatial["Moran_I"]))
    add_validation("EJBI Moran I",sm["EJBI"],EXPECTED["ejbi_moran_i"],0.002)
    add_validation("Primary OBI Moran I",sm["OBI_MCC"],EXPECTED["obi_moran_i"],0.002)
    save_csv_export(validation, "v7_validation_report.csv", category="validation", index=False)
    save_figures(tracts, counties, tables)

    summary = {
        "script_version": SCRIPT_VERSION,
        "study_period": [STUDY_START, STUDY_END],
        "run_started": started.isoformat(),
        "run_finished": datetime.now().isoformat(),
        "tract_geometries": int(len(tracts)),
        "strict_EJBI_tracts": int(tracts["EJBI"].notna().sum()),
        "high_EJBI_tracts": int((tracts["EJBI"]>=TRACT_HIGH_EJBI_THRESHOLD).sum()),
        "counties": int(len(counties)),
        "high_EJBI_counties": int((counties["EJBI"]>=COUNTY_HIGH_EJBI_THRESHOLD).sum()),
        "clean_reconstructed_episodes_2018_2023": int(len(episodes)),
        "MCC_complete_counties": int(counties["modeled_customers"].notna().sum()),
        "primary_OBI_complete_counties": int(counties["OBI_MCC"].notna().sum()),
        "EIA861_in_primary_OBI": False,
        "EIA861_historical_sensitivity_included": True,
        "EIA861_sensitivity_min_annual_reporting_coverage_pct": 80,
        "EIA861_sensitivity_min_qualifying_years": 4,
        "GRIP_in_locked_results": False,
        "hidden_high_EJBI_tracts": int(rem["hidden_high_EJBI_tracts"]),
        "SVI_EJBI_Pearson_r": float(rem["SVI_EJBI_Pearson_r"]),
        "SVI_EJBI_agreement_pct": float(rem["SVI_EJBI_agreement_pct"]),
        "EJBI_Moran_I": float(sm["EJBI"]),
        "Primary_OBI_Moran_I": float(sm["OBI_MCC"]),
        "validation_passed": bool(validation["pass"].all()),
    }
    with open(OUT/"v7_run_summary.json","w",encoding="utf-8") as f:
        json.dump(summary,f,indent=2)

    # Final artifact audit: the run is not complete unless expected deliverables exist.
    publication_dir = FIG / "publication"
    preview_dir = FIG / "preview_300dpi"
    expected_core = [
        OUT / "v7_run_summary.json",
        OUT / "v7_validation_report.csv",
        OUT / "v7_tract_metrics.csv",
        OUT / "v7_county_metrics.csv",
        OUT / "v7_OBI_sensitivity_correlations.csv",
        OUT / "v7_bootstrap_correlation_CIs.csv",
    ]
    expected_core += [OUT / f"v7_Table_{n}.csv" for n in ["II","III","IV","V","VI"]]
    figure_files = sorted(publication_dir.glob("*")) if publication_dir.exists() else []
    preview_files = sorted(preview_dir.glob("*")) if preview_dir.exists() else []

    artifact_audit = {
        "core_files": {str(p.relative_to(OUT)): p.exists() and p.stat().st_size > 0 for p in expected_core},
        "publication_figure_count": len(figure_files),
        "preview_figure_count": len(preview_files),
        "publication_figures": [p.name for p in figure_files],
        "preview_figures": [p.name for p in preview_files],
    }
    expected_figure_count = 16
    expected_publication_files = expected_figure_count * 3  # PDF + SVG + 600-dpi PNG
    expected_preview_files = expected_figure_count           # 300-dpi PNG

    artifact_audit["expected_figure_count"] = expected_figure_count
    artifact_audit["expected_publication_files"] = expected_publication_files
    artifact_audit["expected_preview_files"] = expected_preview_files
    artifact_audit["pass"] = (
        all(artifact_audit["core_files"].values())
        and artifact_audit["publication_figure_count"] == expected_publication_files
        and artifact_audit["preview_figure_count"] == expected_preview_files
    )
    with open(MANIFEST_DIR / "artifact_audit.json", "w", encoding="utf-8") as f:
        json.dump(artifact_audit, f, indent=2)

    if not artifact_audit["pass"]:
        raise RuntimeError(
            "Artifact audit failed: the complete output set was not created. "
            f"Expected 48 publication figure files and 16 previews. "
            f"See {MANIFEST_DIR / 'artifact_audit.json'}"
        )

    zip_path = finalize_export_bundle()

    # Final export manifest after ZIP creation.
    export_manifest = {
        "script_version": SCRIPT_VERSION,
        "eaglei_input_filename": "eaglei_transformed.csv",
        "output_directory": str(OUT),
        "zip_file": str(zip_path),
        "publication_figure_files": artifact_audit["publication_figure_count"],
        "preview_figure_files": artifact_audit["preview_figure_count"],
        "root_csv_files": sorted([p.name for p in OUT.glob("*.csv")]),
        "root_json_files": sorted([p.name for p in OUT.glob("*.json")]),
        "export_pass": True,
    }
    with open(MANIFEST_DIR / "final_export_manifest.json", "w", encoding="utf-8") as f:
        json.dump(export_manifest, f, indent=2)

    print("\nLOCKED PRIMARY RESULTS")
    print("-"*78)
    print(tables[0].to_string(index=False))
    print("\nCORRELATIONS")
    print(tables[3].to_string(index=False))
    print("\nVALIDATION")
    print(validation.to_string(index=False))
    print(f"\nOUTPUT DIRECTORY: {OUT}")
    print(f"FIGURES (publication): {FIG / 'publication'}")
    print(f"FIGURES (300-dpi previews): {FIG / 'preview_300dpi'}")
    print(f"DATA PRODUCTS: {DATA_DIR}")
    print(f"TABLES: {TABLE_DIR}")
    print(f"RESULTS: {RESULTS_DIR}")
    print(f"VALIDATION: {VALIDATION_DIR}")
    print(f"DOWNLOADABLE ZIP: {zip_path}")
    print("="*78)

def run_segda():
    """Notebook/Colab-safe public runner."""
    print(f"SEGDA v{SCRIPT_VERSION}")
    print(f"Data directory: {BASE}")
    print(f"Output directory: {OUT}")
    try:
        main()
    except FileNotFoundError as exc:
        print("\nINPUT FILE ERROR")
        print(str(exc))
        print("\nUpload/extract the required SEGDA dataset bundle into the data directory,")
        print("or set SEGDA_DATA_DIR before running the script.")
        raise
    except Exception as exc:
        print(f"\nSEGDA FAILED: {type(exc).__name__}: {exc}")
        raise

if __name__ == "__main__":
    run_segda()